#!/bin/bash

log (){
    >&2 echo "$1"
}

log "command: $CNI_COMMAND"
log "container id: $CNI_CONTAINERID"
log "network ns: $CNI_NETNS"
log "network interface: $CNI_IFNAME"
log "path to cni plugins: $CNI_PATH"

VETH_STORE=/etc/cni/veth_index
check_br=`brctl show|grep -w br0`
if [ -z "$check_br" ]; then
    add_br=`brctl add br br0; ip link set br0 up; ip addr add 10.10.0.1/24 dev br0`;
fi

case $CNI_COMMAND in
ADD)
    network='10.10.0.0/24'
    ip=('10.10.0.2' '10.10.0.3' '10.10.0.4' '10.10.0.5')
    for ipaddress in ${ip[@]}
    do
        ret=`cat /etc/cni/ipallocate | grep -w "$ipaddress"`
        log "ip check: $ret"
        if [ -z $ret ]; then allocate_ip=$ipaddress; break; fi;
    done

    if [ $allocate_ip ];then
        echo "$allocate_ip" >> /etc/cni/ipallocate
        mkdir -p /var/run/netns/
        ln -sfT $CNI_NETNS /var/run/netns/$CNI_CONTAINERID
        index=$(cat $VETH_STORE 2> /dev/null || printf "0\n")
        index=$((index + 1))
        echo $index > $VETH_STORE
        host_if_name="veth$index"
        temp_if_name="veth_c_$index"
        ip link add $temp_if_name type veth peer name $host_if_name
        ip link set $host_if_name up
        ip link set $host_if_name master br0
        ip link set $temp_if_name netns $CNI_CONTAINERID
        ip netns exec $CNI_CONTAINERID ip link set $temp_if_name name $CNI_IFNAME
        ip netns exec $CNI_CONTAINERID ip link set $CNI_IFNAME up
        ip netns exec $CNI_CONTAINERID ip addr add $allocate_ip/24 dev $CNI_IFNAME
        ip netns exec $CNI_CONTAINERID ip route add default via 10.10.0.1 dev $CNI_IFNAME
        mac=$(ip netns exec $CNI_CONTAINERID ip link show $CNI_IFNAME | awk '/ether/ {print $2}')
    echo "{
  \"cniVersion\": \"0.3.1\",
  \"interfaces\": [
    {
      \"name\": \"$CNI_IFNAME\",
      \"mac\": \"$mac\",
      \"sandbox\": \"$CNI_NETNS\"
    }
  ],
  \"ips\": [
    {
      \"version\": \"4\",
      \"address\": \"$allocate_ip/24\",
      \"gateway\": \"10.10.0.1\",
      \"interface\": 0
    }
  ]
}"
    fi;

    ;;

DEL)
    if [ -z "$CNI_NETNS" ];then
        exit
    fi
    ip=$(ip netns exec $CNI_CONTAINERID ip addr show $CNI_IFNAME | awk '/inet / {print $2}' | sed s%/.*%% || echo "")
    if [ ! -z "$ip" ]
    then
        sed -i "/$ip/d" /etc/cni/ipallocate
        unlink /var/run/netns/$CNI_CONTAINERID
    fi

    echo '{}'
    ;;

CHECK)
    echo '{}'
    ;;

VERSION)
    echo '{"cniVersion": "0.3.1", "supportedVersions": ["0.3.0", "0.3.1"]}'
    ;;

*)
    echo 'unkonwn cmd'
    exit
    ;;

esac
